/**
 * The bundled sample dataset.
 *
 * Every first-time visitor sees this file before they see anything of their
 * own, so a malformed one means a broken first impression. It is generated by a
 * script rather than written by hand, which is exactly the kind of artefact
 * that drifts silently — these tests pin the contract between the generator and
 * the loader in `data/sample.ts`.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

interface CompactReading {
  i: string;
  d: string;
  t: string;
  r: string;
  la: number;
  lo: number;
  tp: (number | null)[];
  tt: (number | null)[];
  at: number | null;
  hu: number | null;
  bv: number | null;
  x: Record<string, unknown>;
}

interface Payload {
  version: number;
  devices: { id: string; name: string }[];
  readings: CompactReading[];
}

const payload = JSON.parse(
  readFileSync(new URL('../public/data/sample-telemetry.json', import.meta.url), 'utf8'),
) as Payload;

describe('sample telemetry', () => {
  it('declares the version the loader expects', () => {
    assert.equal(payload.version, 1);
  });

  it('ships devices and readings', () => {
    assert.ok(payload.devices.length >= 1, 'at least one device');
    assert.ok(payload.readings.length > 500, `only ${payload.readings.length} readings`);
  });

  it('references only devices it also ships', () => {
    const ids = new Set(payload.devices.map((device) => device.id));
    for (const reading of payload.readings) {
      assert.ok(ids.has(reading.d), `reading ${reading.i} references unknown device ${reading.d}`);
    }
  });

  it('uses unique reading ids', () => {
    const ids = new Set(payload.readings.map((reading) => reading.i));
    assert.equal(ids.size, payload.readings.length, 'duplicate ids would silently overwrite');
  });

  it('is ordered by time, which the store relies on', () => {
    for (let index = 1; index < payload.readings.length; index += 1) {
      assert.ok(
        payload.readings[index - 1]!.t <= payload.readings[index]!.t,
        `out of order at index ${index}`,
      );
    }
  });

  it('carries parseable UTC timestamps', () => {
    for (const reading of payload.readings.slice(0, 50)) {
      assert.ok(reading.t.endsWith('Z'), `${reading.t} is not UTC`);
      assert.ok(Number.isFinite(Date.parse(reading.t)));
      assert.ok(Number.isFinite(Date.parse(reading.r)));
    }
  });

  it('holds coordinates inside the valid range', () => {
    for (const reading of payload.readings) {
      assert.ok(reading.la >= -90 && reading.la <= 90, `latitude ${reading.la}`);
      assert.ok(reading.lo >= -180 && reading.lo <= 180, `longitude ${reading.lo}`);
    }
  });

  it('holds four tyre pressures and four tyre temperatures per reading', () => {
    for (const reading of payload.readings.slice(0, 200)) {
      assert.equal(reading.tp.length, 4);
      assert.equal(reading.tt.length, 4);
    }
  });

  it('holds physically plausible sensor values', () => {
    for (const reading of payload.readings) {
      for (const pressure of reading.tp) {
        if (pressure === null) continue;
        assert.ok(pressure >= 0 && pressure <= 1400, `tyre pressure ${pressure}`);
      }
      if (reading.at !== null) {
        assert.ok(reading.at >= -90 && reading.at <= 70, `ambient ${reading.at}`);
      }
      if (reading.hu !== null) {
        assert.ok(reading.hu >= 0 && reading.hu <= 100, `humidity ${reading.hu}`);
      }
      if (reading.bv !== null) {
        assert.ok(reading.bv >= 0 && reading.bv <= 60, `battery ${reading.bv}`);
      }
    }
  });

  it('includes extra fields, so the raw-value view has something to show', () => {
    const withExtras = payload.readings.filter(
      (reading) => reading.x && Object.keys(reading.x).length > 0,
    );
    assert.ok(withExtras.length > 0, 'no reading carries extra device fields');
  });

  it('stays small enough to ship', () => {
    const bytes = readFileSync(
      new URL('../public/data/sample-telemetry.json', import.meta.url),
    ).byteLength;
    // It is fetched lazily and only once, but an unbounded file would still be
    // a poor first load.
    assert.ok(bytes < 2_000_000, `${(bytes / 1024).toFixed(0)} KiB is too large`);
  });
});
